### ISSUE TITLE
Hoozay!

### ISSUE THREAD

**Issue by alexeiva** [davelab6/type-notes#1]
╔♫╗────────╔═╦╗─♫╗╔╗─╔╗────
║╩╠═╦═╦═╦╦╗║╚╠╬╦╣╚╣╚╦╝╠═╦╦╗
║╦║╬║╬║╬║║║║╔║║╔╣╔╣║║╬║╬║║║
╚╩╩╩╣╔╣╔╬╗║♫═╩╩╝╚═╩╩╩═╩╩╬╗║
────♫╝╚╝╚═╝─────────────╚═♫
@davelab6!

**Comment by davelab6** [comment]
haha thanks Alexei! :)
